// Code generated by go generate in tools; DO NOT EDIT.
// Generated at: 2024-05-15T22:14:40-04:00
package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type DiscordPermissionModel struct {
	AllowExtends              types.Int64  `tfsdk:"allow_extends"`
	DenyExtends               types.Int64  `tfsdk:"deny_extends"`
	AllowBits                 types.Int64  `tfsdk:"allow_bits"`
	DenyBits                  types.Int64  `tfsdk:"deny_bits"`
	ManageMessages            types.String `tfsdk:"manage_messages"`
	UseApplicationCommands    types.String `tfsdk:"use_application_commands"`
	SendThreadMessages        types.String `tfsdk:"send_thread_messages"`
	SendVoiceMessages         types.String `tfsdk:"send_voice_messages"`
	CreateExpressions         types.String `tfsdk:"create_expressions"`
	ManageGuild               types.String `tfsdk:"manage_guild"`
	AddReactions              types.String `tfsdk:"add_reactions"`
	DeafenMembers             types.String `tfsdk:"deafen_members"`
	RequestToSpeak            types.String `tfsdk:"request_to_speak"`
	UseExternalStickers       types.String `tfsdk:"use_external_stickers"`
	ModerateMembers           types.String `tfsdk:"moderate_members"`
	BanMembers                types.String `tfsdk:"ban_members"`
	Stream                    types.String `tfsdk:"stream"`
	MentionEveryone           types.String `tfsdk:"mention_everyone"`
	ManageEmojis              types.String `tfsdk:"manage_emojis"`
	PrioritySpeaker           types.String `tfsdk:"priority_speaker"`
	SendMessages              types.String `tfsdk:"send_messages"`
	CreatePrivateThreads      types.String `tfsdk:"create_private_threads"`
	ViewMonetizationAnalytics types.String `tfsdk:"view_monetization_analytics"`
	UseExternalSounds         types.String `tfsdk:"use_external_sounds"`
	Connect                   types.String `tfsdk:"connect"`
	UseVad                    types.String `tfsdk:"use_vad"`
	CreateInstantInvite       types.String `tfsdk:"create_instant_invite"`
	KickMembers               types.String `tfsdk:"kick_members"`
	ViewChannel               types.String `tfsdk:"view_channel"`
	SendTtsMessages           types.String `tfsdk:"send_tts_messages"`
	EmbedLinks                types.String `tfsdk:"embed_links"`
	ViewGuildInsights         types.String `tfsdk:"view_guild_insights"`
	CreateEvents              types.String `tfsdk:"create_events"`
	Administrator             types.String `tfsdk:"administrator"`
	ManageNicknames           types.String `tfsdk:"manage_nicknames"`
	ManageRoles               types.String `tfsdk:"manage_roles"`
	ManageThreads             types.String `tfsdk:"manage_threads"`
	StartEmbeddedActivities   types.String `tfsdk:"start_embedded_activities"`
	ManageEvents              types.String `tfsdk:"manage_events"`
	ManageChannels            types.String `tfsdk:"manage_channels"`
	ViewAuditLog              types.String `tfsdk:"view_audit_log"`
	AttachFiles               types.String `tfsdk:"attach_files"`
	Speak                     types.String `tfsdk:"speak"`
	MuteMembers               types.String `tfsdk:"mute_members"`
	MoveMembers               types.String `tfsdk:"move_members"`
	ReadMessageHistory        types.String `tfsdk:"read_message_history"`
	UseExternalEmojis         types.String `tfsdk:"use_external_emojis"`
	ChangeNickname            types.String `tfsdk:"change_nickname"`
	ManageWebhooks            types.String `tfsdk:"manage_webhooks"`
	CreatePublicThreads       types.String `tfsdk:"create_public_threads"`
	UseSoundboard             types.String `tfsdk:"use_soundboard"`
}
