// Code generated by go generate in tools; DO NOT EDIT.
// Generated at: 2025-02-01T21:25:19-05:00

package provider

import (
	"context"
	"fmt"
	"github.com/Cyb3r-Jak3/discord-terraform/internal/utils"
	"github.com/bwmarrin/discordgo"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64default"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &DiscordTextChannelResource{}
var _ resource.ResourceWithImportState = &DiscordTextChannelResource{}

func NewDiscordNewsChannelResource() resource.Resource {
	return &DiscordNewsChannelResource{}
}

type DiscordNewsChannelResource struct {
	client *Context
}

func (r *DiscordNewsChannelResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_news_channel"
}

func (r *DiscordNewsChannelResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Discord News Channel Resource",

		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description: "The channel ID",
				Computed:    true,
			},
			"server_id": schema.StringAttribute{
				Description: "The server ID",
				Required:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"name": schema.StringAttribute{
				Description: "The channel name",
				Required:    true,
			},
			"channel_id": schema.StringAttribute{
				Description: "The channel ID",
				Computed:    true,
			},
			"type": schema.StringAttribute{
				Description:        "The channel type",
				Optional:           true,
				DeprecationMessage: "This field is deprecated. Type is now inferred from the resource name.",
				Computed:           true,
			},
			"position": schema.Int64Attribute{
				Description: "Sorting position of the channel",
				Optional:    true,
				Default:     int64default.StaticInt64(1),
				Computed:    true,
				Validators: []validator.Int64{
					int64validator.AtLeast(0),
				},
			},
			"sync_perms_with_category": schema.BoolAttribute{
				Description: "Whether to sync permissions with the category",
				Optional:    true,
				Default:     booldefault.StaticBool(true),
				Computed:    true,
			},
			"permissions_synced": schema.BoolAttribute{
				Description: "Whether the permissions are synced with the category",
				Computed:    true,
			},
			"category": schema.StringAttribute{
				Description: "The category ID",
				Optional:    true,
				Computed:    true,
			},
			"topic": schema.StringAttribute{
				Description: "The channel topic",
				Optional:    true,
			}},
	}
}

func (r *DiscordNewsChannelResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*Context)

	if !ok {
		resp.Diagnostics.AddError(
			"unexpected resource configure type",
			fmt.Sprintf("Expected *Context, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
}

type DiscordNewsChannel struct {
	ID                    types.String `tfsdk:"id"`
	ServerID              types.String `tfsdk:"server_id"`
	ChannelID             types.String `tfsdk:"channel_id"`
	Type                  types.String `tfsdk:"type"`
	Name                  types.String `tfsdk:"name"`
	Position              types.Int64  `tfsdk:"position"`
	SyncPermsWithCategory types.Bool   `tfsdk:"sync_perms_with_category"`
	Category              types.String `tfsdk:"category"`
	PermissionsSynced     types.Bool   `tfsdk:"permissions_synced"`
	Topic                 types.String `tfsdk:"topic"`
}

func (r *DiscordNewsChannelResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data *DiscordNewsChannel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}
	client := r.client.Session
	channelParams, err := buildNewsChannelParams(data)
	if err != nil {
		resp.Diagnostics.AddError("Failed to build channel params", err.Error())
		return
	}
	channel, err := client.GuildChannelCreateComplex(data.ServerID.ValueString(), channelParams, discordgo.WithContext(ctx))
	if err != nil {
		resp.Diagnostics.AddError("Failed to create a channel", err.Error())
		return
	}
	data, err = buildNewsChannelModel(channel, data.SyncPermsWithCategory)
	if err != nil {
		resp.Diagnostics.AddError("Failed to build channel model", err.Error())
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *DiscordNewsChannelResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data *DiscordNewsChannel

	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}
	client := r.client.Session
	channel, err := client.Channel(data.ChannelID.ValueString(), discordgo.WithContext(ctx))
	if err != nil {
		resp.Diagnostics.AddError("Failed to fetch channel", err.Error())
		return
	}

	data, err = buildNewsChannelModel(channel, data.SyncPermsWithCategory)
	if err != nil {
		resp.Diagnostics.AddError("Failed to build channel model", err.Error())
		return
	}
	if channel.ParentID == "" {
		data.PermissionsSynced = types.BoolNull()
	} else {
		parent, err := client.Channel(channel.ParentID)
		if err != nil {
			resp.Diagnostics.AddError("Failed to fetch category of channel", err.Error())
			return
		}

		data.PermissionsSynced = types.BoolValue(utils.ArePermissionsSynced(channel, parent))
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *DiscordNewsChannelResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data *DiscordNewsChannel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	client := r.client.Session
	channel, err := client.Channel(data.ChannelID.ValueString(), discordgo.WithContext(ctx))
	if err != nil {
		resp.Diagnostics.AddError("Failed to fetch channel", err.Error())
		return
	}

	channelParams, err := buildNewsChannelParams(data)
	if err != nil {
		resp.Diagnostics.AddError("Failed to build channel params", err.Error())
		return

	}
	if data.SyncPermsWithCategory.ValueBool() {
		if channel.ParentID == "" {
			resp.Diagnostics.AddError("Channel does not have a category", "")
			return
		}

		parent, err := client.Channel(channel.ParentID)
		if err != nil {
			resp.Diagnostics.AddError("Failed to fetch category of channel", err.Error())
			return
		}

		if !utils.ArePermissionsSynced(channel, parent) {
			if err := utils.SyncChannelPermissions(client, ctx, parent, channel); err != nil {
				resp.Diagnostics.AddError("Failed to sync permissions with category", err.Error())
				return
			}
		}
	}

	channel, err = client.ChannelEditComplex(data.ChannelID.ValueString(), &discordgo.ChannelEdit{
		Name:     channelParams.Name,
		Position: &channelParams.Position,
		Topic:    channelParams.Topic,
		ParentID: channelParams.ParentID,
	}, discordgo.WithContext(ctx))
	if err != nil {
		resp.Diagnostics.AddError("Failed to update channel", err.Error())
		return
	}

	data, err = buildNewsChannelModel(channel, data.SyncPermsWithCategory)
	if err != nil {
		resp.Diagnostics.AddError("Failed to build channel model", err.Error())
		return
	}
	if channel.ParentID == "" {
		data.PermissionsSynced = types.BoolNull()
	} else {
		parent, err := client.Channel(channel.ParentID)
		if err != nil {
			resp.Diagnostics.AddError("Failed to fetch category of channel", err.Error())
			return
		}

		data.PermissionsSynced = types.BoolValue(utils.ArePermissionsSynced(channel, parent))
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *DiscordNewsChannelResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data *DiscordNewsChannel

	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}
	client := r.client.Session

	if _, err := client.ChannelDelete(data.ChannelID.ValueString(), discordgo.WithContext(ctx)); err != nil {
		resp.Diagnostics.AddError("Failed to delete channel", err.Error())
		return
	}
}

func (r *DiscordNewsChannelResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	client := r.client.Session
	channel, err := client.Channel(req.ID)
	if err != nil {
		resp.Diagnostics.AddError("Failed to fetch channel", err.Error())
		return
	}
	if channel.ParentID == "" {
		resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("sync_perms_with_category"), false)...)
	} else {
		parent, err := client.Channel(channel.ParentID)
		if err != nil {
			resp.Diagnostics.AddError("Failed to fetch category of channel", err.Error())
			return
		}
		resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("sync_perms_with_category"), types.BoolValue(utils.ArePermissionsSynced(channel, parent)))...)
	}
	resource.ImportStatePassthroughID(ctx, path.Root("channel_id"), req, resp)
}

func buildNewsChannelParams(data *DiscordNewsChannel) (discordgo.GuildChannelCreateData, error) {
	if data.Type.ValueString() == "" {
		data.Type = types.StringValue("news")
	}
	channelType, okay := utils.GetDiscordChannelType(data.Type.ValueString())
	if !okay {
		return discordgo.GuildChannelCreateData{}, fmt.Errorf("invalid channel type: %s", data.Type.ValueString())
	}
	return discordgo.GuildChannelCreateData{
		Name:     data.Name.ValueString(),
		Position: int(data.Position.ValueInt64()),
		Type:     channelType,
		Topic:    data.Topic.ValueString(),
		ParentID: data.Category.ValueString(),
	}, nil

}

func buildNewsChannelModel(channel *discordgo.Channel, SyncPermsWithCategory types.Bool) (*DiscordNewsChannel, error) {
	channelType, okay := utils.GetTextChannelType(channel.Type)
	if !okay {
		return &DiscordNewsChannel{}, fmt.Errorf("invalid channel type: %s", channelType)
	}

	return &DiscordNewsChannel{
		ID:                    types.StringValue(channel.ID),
		ServerID:              types.StringValue(channel.GuildID),
		ChannelID:             types.StringValue(channel.ID),
		Type:                  types.StringValue(channelType),
		Name:                  types.StringValue(channel.Name),
		Position:              types.Int64Value(int64(channel.Position)),
		Category:              types.StringValue(channel.ParentID),
		SyncPermsWithCategory: SyncPermsWithCategory,
		Topic:                 types.StringValue(channel.Topic),
	}, nil
}
